home/urls.py
from django.conf.urls import url
from home.views import HomeView, OrganisationsView, ProjetsView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^organisations/$', OrganisationsView.as_view(), name="organisations"),
    url(r'^projets/$', ProjetsView.as_view(), name="projets"),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mysite import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^projets/', include('projets.urls', namespace="projets")),
    url(r'^organisations/', include('organisations.urls', namespace="organisations")),
    url(r'^$', views.home_redirect, name="home_redirect"),
    url(r'^home/', include('home.urls', namespace="home")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projets/urls.py
from django.conf.urls import url
from projets.views import HomeView, SoumissionView, ProjetView, ProjetCreateView, SoumissionView
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/home/projets', permanent=False), name="redirect"),
    url(r'^(?P<pk>\d+)/$', ProjetView.as_view(), name='projet'),
    url(r'^gestion/$', ProjetCreateView.as_view(), name='projet_create'),
    url(r'^(?P<pk>\d+)/soumission$', SoumissionView.as_view(), name='soumission'),
]

projets/models.py
from organisations.models import Organisation
from django.contrib.gis.db import models

class Zone(models.Model):

    meta = models.CharField('META', max_length=50)
    nom = models.TextField('Nom')
    description = models.TextField('Description')
    url = models.URLField('En savoir plus : ', max_length=300)

    # Par défaut ESPG : WGS84 (srid=4326)
    mpoly = models.MultiPolygonField()

    # Returns the string representation of the model.
    def __str__(self):
        return self.nom

    class Meta:
        verbose_name_plural = "zones"


class Projet(models.Model):

    CATEGORIES = (
            ('FO','Forêt'),
            ('EA','Eau'),
            ('AN','Animaux'),
            ('AI','Air'),
            ('IN','Insectes'),
            ('PL','Plantes'),
            ('RC','Rechauffement climatique'),
            ('NA','Aucune'),
            )

    categorie = models.CharField(max_length=10,choices=CATEGORIES,default='NA')
    nom = models.CharField(max_length=150, default='')
    description = models.TextField(default='')
    organisation = models.ForeignKey(Organisation)
    zone = models.ForeignKey(Zone, blank=True, null=True)
    image = models.ImageField(upload_to='projets_image', blank=True, null=True)

    def __str__(self):
        return self.nom

    class Meta:
        verbose_name_plural = "projets"

class Soumission(models.Model):

    TYPE_FICHIER = (
            ('TX','Texte'),
            ('IM','Image'),
            ('PD','PDF'),
            ('AU','Autre'),
            ('FC','Feuille de calcul'),
            )
    type_fichier = models.CharField(max_length=2,choices=TYPE_FICHIER,default='AU')
    projet = models.ForeignKey(Projet)
    nom = models.CharField(max_length=50)
    email = models.CharField(max_length=75, blank=True, null=True)
    fichier = models.FileField(upload_to='soumission')

    def __str__(self):
        return self.nom

    class Meta:
        verbose_name_plural = "soumissions"

projets/forms.py
from django.forms import ModelForm
from projets.models import Projet, Soumission

class ProjetForm(ModelForm):
    class Meta:
        model = Projet
        fields = ['organisation','nom','description','zone','categorie']

class SoumissionForm(ModelForm):
    class Meta:
        model = Soumission
        fields = ['type_fichier','nom','email','fichier']

projets/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from projets.models import Projet, Zone, Soumission
from organisations.models import Organisation
from projets.forms import ProjetForm, SoumissionForm
from django.urls import reverse
from django.http import HttpResponseRedirect
#import re
import json

class HomeView(TemplateView):
    template_name = 'projets/home.html'

    def get(self, request):
        return render(request, self.template_name)

class SoumissionView(TemplateView):
    template_name = 'projets/soumission.html'

    def get(self, request, pk):
        
        form = SoumissionForm()
        args = {'form':form}

        return render(request, self.template_name, args)


    def post(self, request, pk):

        form = SoumissionForm(request.POST, request.FILES)

        if form.is_valid():
            sub = form.save(commit=False)
            sub.projet = Projet.objects.get(pk=pk)
            sub.save()
            return redirect(reverse('home:home'))



class ProjetView(TemplateView):
    template_name = 'projets/projet.html'

    def get(self, request, pk):
        projet = Projet.objects.get(pk=pk)
        org = Organisation.objects.get(id=projet.organisation_id)
        soumissions = Soumission.objects.filter(projet_id=projet.id)
        

        if projet.zone_id is not None:
            zone_id=projet.zone_id
            poly = Zone.objects.get(id=zone_id).mpoly.json #.split('{"type": "MultiPolygon", "coordinates":', 1)[1]
            dic = json.loads(poly)
            poly_fix = dic['coordinates']
        
        else:
            poly_fix = None
        
        args = {'projet' : projet, 'org' : org, 'poly' : poly_fix, 'soumissions' : soumissions,}

        return render(request, self.template_name, args)
 
class ProjetCreateView(TemplateView):
    template_name = 'projets/projet_create.html'

    def get(self, request):
        form = ProjetForm()
        args = {'form':form}
        
        return render(request, self.template_name, args)

    def post(self, request):    
        
        form = ProjetForm(request.POST)
        
        if form.is_valid():

            form.save()
            return redirect(reverse('home:home'))

projets/templates/projets/projet.html
{% extends 'base.html' %}
<!-- Page d'un projet -->
{% block cards %}
<br/>
<div class="container proj">
  <div class="row">
    <div class="col-sm-12">
	    <h2>{{ projet }}</h2>
	    <h5>{{ org }}</h5>
      <hr>
    </div>
  </div>
  <div class="row description">
    <div class="col-sm-8">
	    <h4>Description</h4>
	    <p class="desc">{{ projet.description }}</p>
    </div>
    <div class="col-sm-4">
	    {% if projet.image %}<img class="img-fluid" style="max-width: 100%;" src="{{ projet.image.url }}" alt="image projet" />{% endif %}
    </div>
  </div>
  <div class="row initiated_projects">
    <div class="col-md-12">
      <h4>Carte</h4>
      <hr>
      <!-- Insert the Google Map -->
	<div class="container proj_map_container">
              <div class="row">
                <div id="map"></div>
                <div class="row">
                  <div class="col-lg-6">
                    <a href="soumission" class="btn btn-primary">Soumettre mes résultats</a>
                  </div>
                </div>
                <script type="text/javascript">
                  showMap(0, 0);
                  if (navigator.geolocation) {
                      if(navigator.geolocation.getCurrentPosition(showPosition)) {
                        //It worked, nothing more to do
                      } else {
                        map.setCenter(45.5017, -73.5673);
                      }
                  }
                  function showPosition(position) {
                    map.setCenter(position.coords.latitude, position.coords.longitude);
                  }
                  var map, path, paths;
                  function showMap(lat, lng){
                    map = new GMaps({
                      el: '#map',
                      lat: lat,
                      lng: lng,
                      zoom: 0,
                    });
                  }
                  map.drawPolygon({
                    paths: {{ poly }}, 
		    useGeoJSON: true,
                    strokeColor: '#131540',
                    strokeOpacity: 0.6,
                    strokeWeight: 6
                  });
                </script>
              </div>
            </div>
    </div>
  </div>
  <div class="row new_entry">
    <div class="col-md-12">
      <h4>Soumissions</h4>
      <hr>
	{% if soumissions %}
		{% for s in soumissions %}
			
<div class="row justify-content-center row_sub">

    <div class="col-sm-6">

      <h4>{{ s.get_type_fichier_display }}</h4>

      <p>{{ s.nom }} | {{ s.email }}</p>

    </div>

  </div>

  <div class="row justify-content-center">

    <div class="col-sm-6">

      <div class="download">

	<p><a download href="/media/{{ s.fichier }}">{{ s }}</a></p>

      </div>

      <hr>

    </div>

  </div>








		{% endfor %}
	{% else %}
		<p>Aucune soumission</p>
	{% endif %}	
    </div>
  </div>
</div>
{% endblock %}

projets/templates/projets/projet_create.html
{% extends 'base.html' %}

      {% block cards %}
      <div class="container" style="margin-bottom: 30px;margin-top: 30px;">
        <div class="row justify-content-md-center" style="text-align: center;">
          <div class="col-md-4">
            <h1>Créez votre projet ici</h1>
            <p style="font-weight: 200;">Création de projet</p>
            <hr>
          </div>
        </div>
        <div class="row justify-content-md-center" style="text-align: center;margin-top: 60px;">
          <div class="col-md-4">
            <h2 style="margin-bottom:15px;">Création de projet</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-primary" style="margin-top:15px;">Soumettre</button>
            </form>
          </div>
        </div>
      </div>
      {% endblock %}

projets/templates/projets/soumission.html
{% extends 'base.html' %}

      {% block cards %}
      <div class="container" style="margin-bottom: 30px;margin-top: 30px;">
        <div class="row justify-content-md-center" style="text-align: center;">
          <div class="col-md-4">
            <h1>Formulaire de soumission</h1>
            <p style="font-weight: 200;">Soumission</p>
            <hr>
          </div>
        </div>
        <div class="row justify-content-md-center" style="text-align: center;margin-top: 60px;">
          <div class="col-md-4">
            <h2 style="margin-bottom:15px;">Soumission</h2>
            <form action="#" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-primary" style="margin-top:15px;">Soumission</button>
            </form>
          </div>
        </div>
      </div>
      {% endblock %}